#!/bin/bash
. ham-bash-lib.sh
. hat default python_27 nodejs
# On separated lines because npm onlyshows a spinner... so you have no idea how long things will take...
ME=${BASH_SOURCE[0]}
NUM_PACKAGES=$( grep npm_install $ME | grep -v '()' | wc -l | xargs )
NUM_INSTALLING=0
NPM_INSTALL_BIN="npm install -g"
NPM_INSTALL="npm install -g --no-bin-links"

# Helpers to install packages
npm_install() {
  local pkg=${1}
  NUM_INSTALLING=$(($NUM_INSTALLING+1))
  echo "I/Installing package '$pkg' ($NUM_INSTALLING/$NUM_PACKAGES)"
  ${NPM_INSTALL} $pkg
}
npm_install_bin() {
  local pkg=${1}
  NUM_INSTALLING=$(($NUM_INSTALLING+1))
  echo "I/Installing package '$pkg' ($NUM_INSTALLING/$NUM_PACKAGES)"
  ${NPM_INSTALL_BIN} $pkg
}

# Install packages, run `$ npm outdated -g` to find latest available.
npm_install_bin 'node-pre-gyp'
npm_install     'webpack@1.x'
npm_install     'webpack-dev-server@1.x'
npm_install_bin 'eslint@3.x'
npm_install     'eslint-plugin-react@3.5.x'
npm_install     'mocha@2.2.x'
npm_install     'react-tools@0.13.x'
npm_install     'css-loader@0.15.x'
npm_install     'jsx-loader@0.13.x'
npm_install     'expose-loader@0.7.3'
npm_install     'extract-text-webpack-plugin@0.8.x'
npm_install     'file-loader@0.8.x'
npm_install     'react@15.1.x react-dom@15.1.x'
npm_install     'react-hot-loader@1.2.x'
npm_install     'react-script-loader@0.0.1'
npm_install     'script-loader@0.6.x'
npm_install     'style-loader@0.12.x'
npm_install     'supertest@1.x'
npm_install     'url-loader@0.5.x'
npm_install     'less@2.5.x less-loader@2.2.x'
npm_install     'nodemon@1.3.7' # 1.3.8 is buggy on Windows
npm_install_bin 'typescript@3.x.x'
npm_install     'awesome-typescript-loader@3.x'
npm_install     'tsd@0.6.x'
npm_install_bin 'react-native-cli@0.1.x'
npm_install_bin 'gulp@3.x'
npm_install_bin 'npm-flatten'
npm_install_bin 'jsonlint@1.6.x'
npm_install     'eslint-plugin-promise@3.5.x'
npm_install_bin '@2fd/graphdoc@2.4.x'
npm_install_bin 'ts-node@7.0.x'
npm_install     'source-map-loader@0.2.x'

echo "I/Listing installed dependencies"
npm list -g --depth 0
